### ISSUE TITLE
Nya gym 

### ISSUE THREAD

**Issue by karben94** [magnusmickelsson/pokeraidbot#13]
Hej(hoppas jag skriver rätt nu, blev lite förvirrad av denna sida)
Vi saknar några gym vid tomtebo/Nydalasjön(varav dom 2 senare ligger lite mer avsides så dom är inte lika viktiga):
Kyrkstugan 63.810025,20.351336,63.810418,20.354264
Klättertorn 63.811989,20.352515, 63.812552,20.354941
Waterhouse by Nydala 63.8177,20.352566, 63.817868,20.355198
Sjökanten 63.819845,20.350845, 63.819339,20.358625

**Comment by karben94** [comment]
@Widdin hej bara kollar så jag inte gjort något fel så ni har missat detta!

**Comment by karben94** [comment]
@magnusmickelsson

**Comment by magnusmickelsson** [comment]
Hej, gymmen i fråga har varit tillagda sedan 6/7, enligt vad jag kan se i Git-annoteringarna.
